version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bigsmoke
      POSTGRES_PASSWORD: grovestreet
    ports:
      - "5432:5432"
  redis:
    image: redis
    command: redis-server
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/chaves/Redis:/var/lib/postgresql/data
  sidekiq:
    build:
      context: .
      dockerfile: dockerfile
    command: bundle exec sidekiq
    depends_on:
      - web      
      - db
      - redis
    volumes:
      - .:/myapp
      - /myapp/temp
    env_file: .env
    environment:
      RAILS_ENV: development
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: circinus
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" && yarn dev
    volumes:
      - .:/myapp
      - /myapp/temp
    ports:
      - "3000:3000"
    links:
      - redis
      - db
    depends_on:
      - redis
      - db

